use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

// [impl->feat~cli-management~1]
// [impl->req~cli-documentation~1]
// [impl->req~cli-profiles-list~1]
// [impl->req~cli-export-ssh-config~1]
// [impl->req~cli-monitor~1]
// [impl->req~cli-shell-completions~1]
// [impl->req~ai-standard-command-compatibility~1]
// [impl->req~rsync-native-sync~1]
// [impl->req~rsync-shim-optional~1]
#[derive(Parser)]
#[command(name = "aether")]
#[command(about = "Aether CLI - Remote terminal and file operations")]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

// [impl->feat~standard-ssh-gateway~1]
// [impl->feat~cli-management~1]
#[derive(Subcommand)]
enum Commands {
    /// List saved connection profiles
    // [impl->req~cli-profiles-list~1]
    Profiles {
        #[arg(long, help = "Output as JSON")]
        json: bool,
    },
    /// Export SSH config for all profiles
    // [impl->req~cli-export-ssh-config~1]
    // [impl->req~ssh-config-generation~1]
    ExportSshConfig,
    /// Connect to a remote host via SSH
    Connect {
        /// Profile name or host
        profile: String,
    },
    /// Execute a command on a remote host
    Exec {
        /// Profile name
        profile: String,
        /// Command to execute
        command: Vec<String>,
    },
    /// Copy files to/from remote host
    Cp {
        /// Source path (local or remote with profile: prefix)
        source: String,
        /// Destination path (local or remote with profile: prefix)
        dest: String,
    },
    /// Create an SSH tunnel
    Tunnel {
        /// Profile name
        profile: String,
        /// Local port forwarding (-L local:remote:host)
        #[arg(short = 'L', value_name = "LOCAL:REMOTE:HOST")]
        local_forward: Option<String>,
        /// Dynamic SOCKS proxy port (-D port)
        #[arg(short = 'D', value_name = "PORT")]
        dynamic: Option<u16>,
    },
    /// Proxy command for SSH credential injection
    // [impl->req~credential-proxy~1]
    SshProxy {
        /// Profile name
        profile: String,
    },
}

// [impl->req~profile-fields~1]
#[derive(Debug, Clone, Serialize, Deserialize)]
struct Profile {
    id: String,
    name: String,
    host: String,
    port: u16,
    username: String,
    auth_type: String,
    private_key_path: Option<String>,
    color: String,
}

#[derive(Debug, Serialize, Deserialize)]
struct ProfilesConfig {
    profiles: Vec<Profile>,
}

fn config_dir() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("aether")
}

fn profiles_path() -> PathBuf {
    config_dir().join("profiles.toml")
}

// [impl->feat~connection-profiles~1]
fn load_profiles() -> anyhow::Result<Vec<Profile>> {
    let path = profiles_path();
    if !path.exists() {
        return Ok(vec![]);
    }
    let contents = std::fs::read_to_string(path)?;
    let config: ProfilesConfig = toml::from_str(&contents)?;
    Ok(config.profiles)
}

fn find_profile(name: &str) -> anyhow::Result<Profile> {
    let profiles = load_profiles()?;
    profiles
        .into_iter()
        .find(|p| p.name == name || p.host == name)
        .ok_or_else(|| anyhow::anyhow!("Profile '{}' not found", name))
}

fn print_profiles_json(profiles: &[Profile]) {
    println!("{}", serde_json::to_string_pretty(profiles).unwrap());
}

fn print_profiles_table(profiles: &[Profile]) {
    if profiles.is_empty() {
        println!("No profiles found.");
        return;
    }
    println!(
        "{:<20} {:<30} {:<10} {:<10}",
        "NAME", "HOST", "PORT", "USER"
    );
    println!("{}", "-".repeat(80));
    for p in profiles {
        println!(
            "{:<20} {:<30} {:<10} {:<10}",
            p.name, p.host, p.port, p.username
        );
    }
}

// [impl->req~ssh-config-generation~1]
fn export_ssh_config(profiles: &[Profile]) {
    println!("# Aether SSH Config - Generated by aether export-ssh-config");
    println!();
    for p in profiles {
        println!("Host {}", p.name);
        println!("    HostName {}", p.host);
        println!("    User {}", p.username);
        println!("    Port {}", p.port);
        if let Some(ref key) = p.private_key_path {
            println!("    IdentityFile {}", key);
        }
        println!();
    }
}

// [impl->feat~cli-management~1]
// [impl->req~cli-documentation~1]
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Profiles { json } => {
            let profiles = load_profiles()?;
            if json {
                print_profiles_json(&profiles);
            } else {
                print_profiles_table(&profiles);
            }
        }
        // [utest->req~ssh-config-generation~1]
        Commands::ExportSshConfig => {
            let profiles = load_profiles()?;
            export_ssh_config(&profiles);
        }
        Commands::Connect { profile } => {
            let p = find_profile(&profile)?;
            println!("Connecting to {}@{}:{}...", p.username, p.host, p.port);
            println!("(Full SSH implementation pending)");
        }
        Commands::Exec { profile, command } => {
            let p = find_profile(&profile)?;
            let cmd = command.join(" ");
            println!("Executing on {}: {}", p.name, cmd);
            println!("(Full SSH implementation pending)");
        }
        Commands::Cp { source, dest } => {
            println!("Copying {} -> {}", source, dest);
            println!("(SFTP implementation pending)");
        }
        Commands::Tunnel {
            profile,
            local_forward,
            dynamic,
        } => {
            let p = find_profile(&profile)?;
            if let Some(lf) = local_forward {
                println!("Tunneling {} -> {}", lf, p.host);
            }
            if let Some(port) = dynamic {
                println!("SOCKS proxy on port {} via {}", port, p.host);
            }
            println!("(Tunnel implementation pending)");
        }
        // [utest->req~credential-proxy~1]
        Commands::SshProxy { profile } => {
            let p = find_profile(&profile)?;
            println!(
                "Proxy for {}@{}:{} (credential injection pending)",
                p.username, p.host, p.port
            );
        }
    }

    Ok(())
}
